server:
  port: 8080
database:
  host: localhost
  port: 5432
  name: corobo
  user: postgres
  password: postgres
keys:
  github_id: github_client_id
  github_secret: github_client_secret
  gitlab_id: gitlab_client_id
  gitlab_secret: gitlab_client_secret
